import type { DesignScreen, ExportFormat, CraftNode } from "@/types/analysis";

const GEMINI_API_URL =
  "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent";

function buildPrompt(screens: DesignScreen[], format: ExportFormat): string {
  const formatInstructions: Record<ExportFormat, string> = {
    "react-tailwind":
      "Generate React functional components using TypeScript and Tailwind CSS utility classes. Use modern React patterns with hooks. Export each screen as a named component.",
    "vue-tailwind":
      "Generate Vue 3 Composition API components using <script setup> and Tailwind CSS utility classes. Export each screen as a separate .vue file.",
    "html-css":
      "Generate clean semantic HTML5 with inline CSS styles. Use flexbox/grid for layout. Make it responsive.",
    "jetpack-compose":
      "Generate Kotlin Jetpack Compose @Composable functions. Use Row, Column, Box, and Material3 components. Include Modifier chains for styling.",
    "kotlin-xml":
      "Generate Android XML layout files using ConstraintLayout and LinearLayout. Use Material Design components where appropriate.",
    json: "Return the design data as a clean, well-structured JSON object.",
  };

  const screensJson = JSON.stringify(
    screens.map((s) => ({
      name: s.name,
      width: s.width,
      height: s.height,
      nodes: simplifyNodes(s.nodes),
    })),
    null,
    2
  );

  return `You are a UI code generator. Convert the following design specification into production-ready code.

FORMAT: ${format}
INSTRUCTIONS: ${formatInstructions[format]}

DESIGN DATA:
${screensJson}

RULES:
- Generate clean, readable, production-quality code
- Use proper naming conventions for the target framework
- Include all necessary imports
- Make layouts responsive where possible
- Use semantic component names based on the element labels
- For Android: use Material3 components
- Return ONLY the code, no explanations

OUTPUT:`;
}

function simplifyNodes(nodes: CraftNode[]): Record<string, unknown>[] {
  return nodes.map((n) => ({
    type: n.type,
    displayName: n.displayName,
    props: n.props,
    children: n.children ? simplifyNodes(n.children) : [],
  }));
}

export async function generateCode(
  screens: DesignScreen[],
  format: ExportFormat
): Promise<string> {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    throw new Error("GEMINI_API_KEY not configured");
  }

  // JSON format: client-side generation (no API call needed)
  if (format === "json") {
    return JSON.stringify(screens, null, 2);
  }

  const prompt = buildPrompt(screens, format);

  const response = await fetch(`${GEMINI_API_URL}?key=${apiKey}`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      contents: [{ parts: [{ text: prompt }] }],
      generationConfig: {
        temperature: 0.2,
        maxOutputTokens: 8192,
      },
    }),
  });

  if (!response.ok) {
    const error = await response.text();
    throw new Error(`Gemini API error: ${response.status} - ${error}`);
  }

  const data = await response.json();
  const text = data.candidates?.[0]?.content?.parts?.[0]?.text;

  if (!text) {
    throw new Error("No code generated by Gemini");
  }

  // Extract code blocks if wrapped in markdown
  const codeBlockMatch = text.match(/```(?:\w+)?\n([\s\S]*?)```/);
  return codeBlockMatch ? codeBlockMatch[1].trim() : text.trim();
}
